// Makes the analytics pages' world map from Natural Earth's 1:110m countries (public domain, naturalearthdata.com):
//   public/world-map.svg        every country's outline in one path (equirectangular, Antarctica left out)
//   src/analytics/countries.ts  each country's label point on that map, by ISO 3166-1 alpha-2 code (GA's countryId)
// Run once by hand; the outputs are committed, so nothing is downloaded at build or run time.
//   node scripts/world-map.ts [path/to/ne_110m_admin_0_countries.geojson]
// Without a path it downloads v5.1.2 of the file from github.com/nvkelso/natural-earth-vector.
import { readFileSync, writeFileSync } from 'node:fs';
import { MAP_HEIGHT, MAP_WIDTH, project } from '../src/analytics/projection.ts';

const SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_admin_0_countries.geojson';
type Ring = [number, number][];
interface Feature { properties: Record<string, string | number | null>; geometry: { type: 'Polygon' | 'MultiPolygon'; coordinates: unknown } }

const file = process.argv[2];
const geo = JSON.parse(file ? readFileSync(file, 'utf8') : await (await fetch(SOURCE)).text()) as { features: Feature[] };
const r = (n: number) => Math.round(n * 10) / 10;
let d = '';
const points: Record<string, [number, number, string]> = {};
for (const f of geo.features) {
  const p = f.properties;
  if (p.ISO_A3 === 'ATA') continue;
  const polys = (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates) as Ring[][];
  for (const poly of polys) for (const ring of poly) {
    let prev = '';
    ring.forEach(([lon, lat], i) => {
      const [x, y] = project(lon, lat);
      const pt = `${r(x)} ${r(y)}`;
      if (pt === prev) return;
      d += `${i ? 'L' : 'M'}${pt}`;
      prev = pt;
    });
    d += 'Z';
  }
  // ISO_A2 is -99 for a few countries (France, Norway, Kosovo); ISO_A2_EH fills those in.
  const code = [p.ISO_A2, p.ISO_A2_EH].find((c) => typeof c === 'string' && /^[A-Z]{2}$/.test(c)) as string | undefined;
  if (code && typeof p.LABEL_X === 'number' && typeof p.LABEL_Y === 'number') {
    const [x, y] = project(p.LABEL_X, p.LABEL_Y);
    points[code] = [r(x), r(y), String(p.NAME)];
  }
}
writeFileSync(new URL('../public/world-map.svg', import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MAP_WIDTH} ${MAP_HEIGHT}"><!-- Natural Earth 1:110m countries (public domain), scripts/world-map.ts --><path d="${d}"/></svg>\n`);
const lines = Object.keys(points).sort().map((k) => `  ${k}: [${points[k][0]}, ${points[k][1]}, ${JSON.stringify(points[k][2])}],`);
writeFileSync(new URL('../src/analytics/countries.ts', import.meta.url),
  `// Generated by scripts/world-map.ts from Natural Earth 1:110m countries (public domain): each country's label point on
// public/world-map.svg (see projection.ts), by ISO 3166-1 alpha-2 code, which is what GA4's countryId dimension holds.
export const COUNTRY_POINTS: Record<string, [x: number, y: number, name: string]> = {
${lines.join('\n')}
};
`);
console.log(`world-map.svg: ${d.length} bytes of path; ${Object.keys(points).length} countries`);
